global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: kvs-seed
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - kvs-server-seed:8080

#  - job_name: kvs-server
#    honor_timestamps: true
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    metrics_path: /metrics
#    scheme: http
#    follow_redirects: true
#    static_configs:
#      - targets:
#          - kvs-server:8080

#  - job_name: prometheus
#    honor_timestamps: true
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    metrics_path: /metrics
#    scheme: http
#    follow_redirects: true
#    static_configs:
#      - targets:
#          - localhost:9090
